# Generated by Django 6.0.3 on 2026-03-29 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_open_for_random_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
