# Generated by Django 6.0.3 on 2026-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_is_open_for_random_join_team_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mentor_invite_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
