# Generated by Django 6.0.3 on 2026-03-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_open_for_teaming',
            field=models.BooleanField(default=False),
        ),
    ]
