<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-26 09:52
=======
# Generated by Django 6.0.5 on 2026-05-26 10:32
>>>>>>> origin/arafat_integration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wins',
<<<<<<< HEAD
            field=models.PositiveIntegerField(default=0),
=======
            field=models.IntegerField(default=0),
>>>>>>> origin/arafat_integration
        ),
    ]
