# Generated by Django 6.0.5 on 2026-05-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_open_for_teaming',
        ),
    ]
