# Generated by Django 6.0.3 on 2026-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('technologies', models.TextField(blank=True, null=True)),
                ('project_url', models.TextField(blank=True, null=True)),
                ('repository_url', models.TextField(blank=True, null=True)),
                ('demo_url', models.TextField(blank=True, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
