# Generated by Django 6.0.3 on 2026-05-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/presentations/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
