# Generated by Django 6.0.3 on 2026-05-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_image_file_project_presentation_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demo_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='video_url',
        ),
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
