# Generated by Django 6.0.3 on 2026-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_demo_url_remove_project_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='youtube_url',
        ),
    ]
