# Generated by Django 6.0.3 on 2026-05-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_url',
        ),
    ]
