# Generated by Django 6.0.3 on 2026-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(choices=[('intra', 'Intra-university'), ('inter', 'Inter-university')], default='intra', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('running', 'Running'), ('judging', 'Judging'), ('finished', 'Finished')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('max_team_size', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hackathons',
            },
        ),
        migrations.CreateModel(
            name='HackathonParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hackathon_participants',
            },
        ),
        migrations.CreateModel(
            name='HackathonStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('registration', 'Registration'), ('team_building', 'Team Building'), ('submission', 'Submission'), ('judging', 'Judging'), ('results', 'Results')], max_length=100)),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'hackathon_stages',
            },
        ),
    ]
