# Generated by Django 6.0.3 on 2026-03-29 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_hackathons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonparticipant',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='hackathons.hackathon'),
        ),
        migrations.AddField(
            model_name='hackathonparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonstage',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='hackathons.hackathon'),
        ),
        migrations.AlterUniqueTogether(
            name='hackathonparticipant',
            unique_together={('hackathon', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='hackathonstage',
            unique_together={('hackathon', 'stage_name')},
        ),
    ]
