# Generated by Django 6.0.3 on 2026-03-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='allow_mentor_assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='allow_random_teaming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='max_mentors_per_team',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='min_team_size',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
