# Generated by Django 6.0.3 on 2026-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_hackathon_allow_mentor_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration'), ('team_building', 'Team Building'), ('submission', 'Submission'), ('judging', 'Judging'), ('finished', 'Finished'), ('archived', 'Archived')], default='draft', max_length=30),
        ),
    ]
