# Generated by Django 6.0.3 on 2026-05-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_remove_hackathon_is_published_alter_hackathon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='hackathons/covers/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='rules_file',
            field=models.FileField(blank=True, null=True, upload_to='hackathons/rules/'),
        ),
    ]
