# Generated by Django 6.0.3 on 2026-05-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0005_hackathon_cover_image_hackathon_rules_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='rules_file',
        ),
        migrations.CreateModel(
            name='HackathonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='hackathons/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hackathons.hackathon')),
            ],
            options={
                'db_table': 'hackathon_attachments',
            },
        ),
    ]
