# Generated by Django 6.0.3 on 2026-03-29 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judging', '0001_initial'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_hackathons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='judging.judge'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='score',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.judgeassignment'),
        ),
        migrations.AddField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.criterion'),
        ),
        migrations.AlterUniqueTogether(
            name='judge',
            unique_together={('hackathon', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='judgeassignment',
            unique_together={('judge', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('assignment', 'criterion')},
        ),
    ]
