# Generated by Django 6.0.3 on 2026-03-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='hackathons.hackathon'),
        ),
    ]
